# Site settings
title: Tata Iles
email: tatailes34@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Make yourself home. Take a seat — I’m serving data recipes, AI experiments, and projects cooked with care."
keywords: "your keywords, separated by commas"
skills: "Data & Automation Engineer : Your manual chaos to automated intelligence."
meta_author: Tata Iles

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6a0dad        # your main purple
  primary-rgb: "106,13,173"  # same color in RGB for overlays
  secondary: 4b0082      # dark purple for contrast
  secondary-dark: 2e004f # very dark purple

# Footer settings
footer:
  copyright: Tata Iles
  location: Algeria
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/iles-tata
  - title: envelope
    url: mailto:tatailes34@gmail.com
  - title : kaggle
    url: https://www.kaggle.com/tatailes
  - title: github
    url: https://github.com/tatailes19

# Postal address (add as many lines as necessary)
address:
  - line: Zeralda
  - line: ALgiers, Algeria
  - line : tatatiles34@gmail.com

# Credits content
credits: 'Built by me upon the Freelancer framework by <a href="http://startbootstrap.com" target="_blank" style="color: var(--primary-purple); font-weight: 700;">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
